notifications:
  email: false
language: Ruby
rvm:
  - 2.3.0
  - 2.4.1
  - 2.5.3
branches:
  only:
    - master
script:
  - bundle install
  - bundle exec rake test
  - gem build ruby_olm.gemspec && gem install self_crypto-*.gem && cd gem_test && rake
