dist: bionic
language: ruby

before_install:
  - curl -O http://download.selfid.net/olm/libself-olm_0.1.14_amd64.deb
  - curl -O http://download.selfid.net/omemo/libself-omemo_0.1.1_amd64.deb
  - sudo apt update
  - sudo apt install libsodium-dev
  - sudo apt install ./libself-olm_0.1.14_amd64.deb
  - sudo apt install ./libself-omemo_0.1.1_amd64.deb

script:
  - bundle install
  - bundle exec rake test
  - gem build self-crypto-ruby.gemspec && CC=clang gem install --verbose self_crypto-*.gem && cd gem_test && rake
